name: Markdown Lint

on:
  push:
    branches:
      - master
    paths:
      - '**.md'
  pull_request:
    branches:
      - master
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  markdownlint:
    name: Lint Markdown files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: '**/*.md'
          config: '.markdownlint.json'
